### ISSUE TITLE
Crash after requestAccess in electron 17 app

### ISSUE THREAD

**Issue by LemonaOna** [codebytere/node-mac-contacts#30] opened 2022-03-21 09:39 UTC
`/Electron exited with signal SIGSEGV`

In our Electron App (v17), we try to get local mac contacts. Getting the auth status works, but after requesting access the app crashes with SIGSEV (BAD ACCESS) signal. The Mac Error report is attached below.

Has anyone made the package work in context of an electron app? Or any ideas?

```Translated Report (Full Report Below)
-------------------------------------

Process:               Electron [10118]
Path:                  /Users/USER/*/Electron.app/Contents/MacOS/Electron
Identifier:            com.github.Electron
Version:               17.1.0 (17.1.0)
Code Type:             X86-64 (Native)
Parent Process:        Exited process [10117]
Responsible:           iTerm2 [5772]
User ID:               503

Date/Time:             2022-03-21 10:21:29.9377 +0100
OS Version:            macOS 12.2.1 (21D62)
Report Version:        12
Bridge OS Version:     6.2 (19P744)
Anonymous UUID:        2BF55624-B432-C2A9-50EA-7CCD488A083C


Time Awake Since Boot: 8700 seconds

System Integrity Protection: enabled

Crashed Thread:        25  Dispatch queue: com.apple.root.background-qos

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [10118]```

**Comment by LemonaOna** [comment] 2022-03-21 09:47
It works in Electron 16. 
Maybe this helps:
https://stackoverflow.com/questions/71344200/node-addon-crashes-in-electron-but-works-fine-in-vanilla-node

**Comment by codebytere** [comment] 2022-03-21 11:03
hey @LemonaOna - could you potentially provide a small reproducible sample of an Electron app that I could run to see this crash? I'm having a hard time reproducing it locally. I've uploaded a small sample I used to attempt a repro on macOS with Electron `v17.1.0`, which worked as expected (giving me a permissions popup and then showing authorized after I approved)

[crash_repro_sample.zip](https://github.com/codebytere/node-mac-contacts/files/8314904/crash_repro_sample.zip)

**Comment by KishanBagaria** [comment] 2022-03-21 11:28
@codebytere tried your zip with no changes, got the SIGSEGV:

```
$ npm start
> snotty-servant-misspell-fyb0d@1.0.0 start
> electron .

Authorization access to contacts is: Authorized
Authorization access to contacts is: Authorized
/Users/kb/Downloads/crash_repro_sample/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGSEGV
$ uname -a
Darwin Kishans-MBP 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64 arm64 MacBookPro18,1 Darwin
```

Contacts access was authorized for iTerm before running it.

**Comment by codebytere** [comment] 2022-03-21 11:31
ah crap - i think i found the issue. I think it's an issue with the version of Node.js bundled into v17.  Bisecting now.

Looks like it stops at `17.1.1` actually - can you both verify as well?

**Comment by KishanBagaria** [comment] 2022-03-21 11:46
Can confirm, `17.1.1+` works fine. Curious what was the issue?

**Comment by LemonaOna** [comment] 2022-03-21 12:09
Yes! We can also confirm that it works with 17.1.1. Thanks a lot !

**Comment by codebytere** [comment] 2022-03-21 14:14
In that case i'll close this out, but please ping if you see it again!

**Closed as completed by codebytere** 2022-03-21 14:14 UTC
Labels: bug
